/*
 * MIT License
 *
 * Copyright (c) 2023 NUbots
 *
 * This file is part of the NUbots codebase.
 * See https://github.com/NUbots/NUbots for further info.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#ifndef MODULE_PLATFORM_OPENCR_SERVOS_HPP
#define MODULE_PLATFORM_OPENCR_SERVOS_HPP

#include <cstdint>

#include "dynamixel/v2/DynamixelDevice.hpp"

namespace module::platform::OpenCR {
    struct DynamixelServo : public DynamixelDevice {
        /**
         * @brief Holds the addresses of the various bytes in the RAM table of a Dynamixel V2 servo.
         *
         * @details
         *  for additional details see
         * http://emanual.robotis.com/docs/en/dxl/mx/mx-64-2/
         * http://emanual.robotis.com/docs/en/dxl/mx/mx-106-2/
         */
        enum class Address : uint16_t {
            MODEL_NUMBER_L          = 0,
            MODEL_NUMBER_H          = 1,
            MODEL_INFORMATION_L     = 2,
            MODEL_INFORMATION_2     = 3,
            MODEL_INFORMATION_3     = 4,
            MODEL_INFORMATION_H     = 5,
            FIRMWARE_VERSION        = 6,
            ID                      = 7,
            BAUD_RATE               = 8,
            RETURN_DELAY_TIME       = 9,
            DRIVE_MODE              = 10,
            OPERATING_MODE          = 11,
            SECONDARY_ID            = 12,
            PROTOCOL_VERSION        = 13,
            HOMING_OFFSET_L         = 20,
            HOMING_OFFSET_2         = 21,
            HOMING_OFFSET_3         = 22,
            HOMING_OFFSET_H         = 23,
            MOVING_THRESHOLD_L      = 24,
            MOVING_THRESHOLD_2      = 25,
            MOVING_THRESHOLD_3      = 26,
            MOVING_THRESHOLD_H      = 27,
            TEMPERATURE_LIMIT       = 31,
            MAX_VOLTAGE_LIMIT_L     = 32,
            MAX_VOLTAGE_LIMIT_H     = 33,
            MIN_VOLTAGE_LIMIT_L     = 34,
            MIN_VOLTAGE_LIMIT_H     = 35,
            PWM_LIMIT_L             = 36,
            PWM_LIMIT_H             = 37,
            CURRENT_LIMIT_L         = 38,
            CURRENT_LIMIT_H         = 39,
            ACCELERATION_LIMIT_L    = 40,
            ACCELERATION_LIMIT_2    = 41,
            ACCELERATION_LIMIT_3    = 42,
            ACCELERATION_LIMIT_H    = 43,
            VELOCITY_LIMIT_L        = 44,
            VELOCITY_LIMIT_2        = 45,
            VELOCITY_LIMIT_3        = 46,
            VELOCITY_LIMIT_H        = 47,
            MAX_POSITION_LIMIT_L    = 48,
            MAX_POSITION_LIMIT_2    = 49,
            MAX_POSITION_LIMIT_3    = 50,
            MAX_POSITION_LIMIT_H    = 51,
            MIN_POSITION_LIMIT_L    = 52,
            MIN_POSITION_LIMIT_2    = 53,
            MIN_POSITION_LIMIT_3    = 54,
            MIN_POSITION_LIMIT_H    = 55,
            SHUTDOWN                = 63,
            TORQUE_ENABLE           = 64,
            LED                     = 65,
            STATUS_RETURN_LEVEL     = 68,
            REGISTERED_INSTRUCTION  = 69,
            HARDWARE_ERROR_STATUS   = 70,
            VELOCITY_I_GAIN_L       = 76,
            VELOCITY_I_GAIN_H       = 77,
            VELOCITY_P_GAIN_L       = 78,
            VELOCITY_P_GAIN_H       = 79,
            POSITION_D_GAIN_L       = 80,
            POSITION_D_GAIN_H       = 81,
            POSITION_I_GAIN_L       = 82,
            POSITION_I_GAIN_H       = 83,
            POSITION_P_GAIN_L       = 84,
            POSITION_P_GAIN_H       = 85,
            FEEDFORWARD_2ND_GAIN_L  = 88,
            FEEDFORWARD_2ND_GAIN_H  = 89,
            FEEDFORWARD_1ST_GAIN_L  = 90,
            FEEDFORWARD_1ST_GAIN_H  = 91,
            BUS_WATCHDOG            = 98,
            GOAL_PWM_L              = 100,
            GOAL_PWM_H              = 101,
            GOAL_CURRENT_L          = 102,
            GOAL_CURRENT_H          = 103,
            GOAL_VELOCITY_L         = 104,
            GOAL_VELOCITY_2         = 105,
            GOAL_VELOCITY_3         = 106,
            GOAL_VELOCITY_H         = 107,
            PROFILE_ACCELERATION_L  = 108,
            PROFILE_ACCELERATION_2  = 109,
            PROFILE_ACCELERATION_3  = 110,
            PROFILE_ACCELERATION_H  = 111,
            PROFILE_VELOCITY_L      = 112,
            PROFILE_VELOCITY_2      = 113,
            PROFILE_VELOCITY_3      = 114,
            PROFILE_VELOCITY_H      = 115,
            GOAL_POSITION_L         = 116,
            GOAL_POSITION_2         = 117,
            GOAL_POSITION_3         = 118,
            GOAL_POSITION_H         = 119,
            REALTIME_TICK_L         = 120,
            REALTIME_TICK_H         = 121,
            MOVING                  = 122,
            MOVING_STATUS           = 123,
            PRESENT_PWM_L           = 124,
            PRESENT_PWM_H           = 125,
            PRESENT_CURRENT_L       = 126,
            PRESENT_CURRENT_H       = 127,
            PRESENT_VELOCITY_L      = 128,
            PRESENT_VELOCITY_2      = 129,
            PRESENT_VELOCITY_3      = 130,
            PRESENT_VELOCITY_H      = 131,
            PRESENT_POSITION_L      = 132,
            PRESENT_POSITION_2      = 133,
            PRESENT_POSITION_3      = 134,
            PRESENT_POSITION_H      = 135,
            VELOCITY_TRAJECTORY_L   = 136,
            VELOCITY_TRAJECTORY_2   = 137,
            VELOCITY_TRAJECTORY_3   = 138,
            VELOCITY_TRAJECTORY_H   = 139,
            POSITION_TRAJECTORY_L   = 140,
            POSITION_TRAJECTORY_2   = 141,
            POSITION_TRAJECTORY_3   = 142,
            POSITION_TRAJECTORY_H   = 143,
            PRESENT_INPUT_VOLTAGE_L = 144,
            PRESENT_INPUT_VOLTAGE_H = 145,
            PRESENT_TEMPERATURE     = 146,
            INDIRECT_ADDRESS_1_L    = 168,
            INDIRECT_ADDRESS_1_H    = 169,
            INDIRECT_ADDRESS_2_L    = 170,
            INDIRECT_ADDRESS_2_H    = 171,
            INDIRECT_ADDRESS_3_L    = 172,
            INDIRECT_ADDRESS_3_H    = 173,
            INDIRECT_ADDRESS_4_L    = 174,
            INDIRECT_ADDRESS_4_H    = 175,
            INDIRECT_ADDRESS_5_L    = 176,
            INDIRECT_ADDRESS_5_H    = 177,
            INDIRECT_ADDRESS_6_L    = 178,
            INDIRECT_ADDRESS_6_H    = 179,
            INDIRECT_ADDRESS_7_L    = 180,
            INDIRECT_ADDRESS_7_H    = 181,
            INDIRECT_ADDRESS_8_L    = 182,
            INDIRECT_ADDRESS_8_H    = 183,
            INDIRECT_ADDRESS_9_L    = 184,
            INDIRECT_ADDRESS_9_H    = 185,
            INDIRECT_ADDRESS_10_L   = 186,
            INDIRECT_ADDRESS_10_H   = 187,
            INDIRECT_ADDRESS_11_L   = 188,
            INDIRECT_ADDRESS_11_H   = 189,
            INDIRECT_ADDRESS_12_L   = 190,
            INDIRECT_ADDRESS_12_H   = 191,
            INDIRECT_ADDRESS_13_L   = 192,
            INDIRECT_ADDRESS_13_H   = 193,
            INDIRECT_ADDRESS_14_L   = 194,
            INDIRECT_ADDRESS_14_H   = 195,
            INDIRECT_ADDRESS_15_L   = 196,
            INDIRECT_ADDRESS_15_H   = 197,
            INDIRECT_ADDRESS_16_L   = 198,
            INDIRECT_ADDRESS_16_H   = 199,
            INDIRECT_ADDRESS_17_L   = 200,
            INDIRECT_ADDRESS_17_H   = 201,
            INDIRECT_ADDRESS_18_L   = 202,
            INDIRECT_ADDRESS_18_H   = 203,
            INDIRECT_ADDRESS_19_L   = 204,
            INDIRECT_ADDRESS_19_H   = 205,
            INDIRECT_ADDRESS_20_L   = 206,
            INDIRECT_ADDRESS_20_H   = 207,
            INDIRECT_ADDRESS_21_L   = 208,
            INDIRECT_ADDRESS_21_H   = 209,
            INDIRECT_ADDRESS_22_L   = 210,
            INDIRECT_ADDRESS_22_H   = 211,
            INDIRECT_ADDRESS_23_L   = 212,
            INDIRECT_ADDRESS_23_H   = 213,
            INDIRECT_ADDRESS_24_L   = 214,
            INDIRECT_ADDRESS_24_H   = 215,
            INDIRECT_ADDRESS_25_L   = 216,
            INDIRECT_ADDRESS_25_H   = 217,
            INDIRECT_ADDRESS_26_L   = 218,
            INDIRECT_ADDRESS_26_H   = 219,
            INDIRECT_ADDRESS_27_L   = 220,
            INDIRECT_ADDRESS_27_H   = 221,
            INDIRECT_ADDRESS_28_L   = 222,
            INDIRECT_ADDRESS_28_H   = 223,
            INDIRECT_DATA_1         = 224,
            INDIRECT_DATA_2         = 225,
            INDIRECT_DATA_3         = 226,
            INDIRECT_DATA_4         = 227,
            INDIRECT_DATA_5         = 228,
            INDIRECT_DATA_6         = 229,
            INDIRECT_DATA_7         = 230,
            INDIRECT_DATA_8         = 231,
            INDIRECT_DATA_9         = 232,
            INDIRECT_DATA_10        = 233,
            INDIRECT_DATA_11        = 234,
            INDIRECT_DATA_12        = 235,
            INDIRECT_DATA_13        = 236,
            INDIRECT_DATA_14        = 237,
            INDIRECT_DATA_15        = 238,
            INDIRECT_DATA_16        = 239,
            INDIRECT_DATA_17        = 240,
            INDIRECT_DATA_18        = 241,
            INDIRECT_DATA_19        = 242,
            INDIRECT_DATA_20        = 243,
            INDIRECT_DATA_21        = 244,
            INDIRECT_DATA_22        = 245,
            INDIRECT_DATA_23        = 246,
            INDIRECT_DATA_24        = 247,
            INDIRECT_DATA_25        = 248,
            INDIRECT_DATA_26        = 249,
            INDIRECT_DATA_27        = 250,
            INDIRECT_DATA_28        = 251,
            INDIRECT_ADDRESS_29_L   = 578,
            INDIRECT_ADDRESS_29_H   = 579,
            INDIRECT_ADDRESS_30_L   = 580,
            INDIRECT_ADDRESS_30_H   = 581,
            INDIRECT_ADDRESS_31_L   = 582,
            INDIRECT_ADDRESS_31_H   = 583,
            INDIRECT_ADDRESS_32_L   = 584,
            INDIRECT_ADDRESS_32_H   = 585,
            INDIRECT_ADDRESS_33_L   = 586,
            INDIRECT_ADDRESS_33_H   = 587,
            INDIRECT_ADDRESS_34_L   = 588,
            INDIRECT_ADDRESS_34_H   = 589,
            INDIRECT_ADDRESS_35_L   = 590,
            INDIRECT_ADDRESS_35_H   = 591,
            INDIRECT_ADDRESS_36_L   = 592,
            INDIRECT_ADDRESS_36_H   = 593,
            INDIRECT_ADDRESS_37_L   = 594,
            INDIRECT_ADDRESS_37_H   = 595,
            INDIRECT_ADDRESS_38_L   = 596,
            INDIRECT_ADDRESS_38_H   = 597,
            INDIRECT_ADDRESS_39_L   = 598,
            INDIRECT_ADDRESS_39_H   = 599,
            INDIRECT_ADDRESS_40_L   = 600,
            INDIRECT_ADDRESS_40_H   = 601,
            INDIRECT_ADDRESS_41_L   = 602,
            INDIRECT_ADDRESS_41_H   = 603,
            INDIRECT_ADDRESS_42_L   = 604,
            INDIRECT_ADDRESS_42_H   = 605,
            INDIRECT_ADDRESS_43_L   = 606,
            INDIRECT_ADDRESS_43_H   = 607,
            INDIRECT_ADDRESS_44_L   = 608,
            INDIRECT_ADDRESS_44_H   = 609,
            INDIRECT_ADDRESS_45_L   = 610,
            INDIRECT_ADDRESS_45_H   = 611,
            INDIRECT_ADDRESS_46_L   = 612,
            INDIRECT_ADDRESS_46_H   = 613,
            INDIRECT_ADDRESS_47_L   = 614,
            INDIRECT_ADDRESS_47_H   = 615,
            INDIRECT_ADDRESS_48_L   = 616,
            INDIRECT_ADDRESS_48_H   = 617,
            INDIRECT_ADDRESS_49_L   = 618,
            INDIRECT_ADDRESS_49_H   = 619,
            INDIRECT_ADDRESS_50_L   = 620,
            INDIRECT_ADDRESS_50_H   = 621,
            INDIRECT_ADDRESS_51_L   = 622,
            INDIRECT_ADDRESS_51_H   = 623,
            INDIRECT_ADDRESS_52_L   = 624,
            INDIRECT_ADDRESS_52_H   = 625,
            INDIRECT_ADDRESS_53_L   = 626,
            INDIRECT_ADDRESS_53_H   = 627,
            INDIRECT_ADDRESS_54_L   = 628,
            INDIRECT_ADDRESS_54_H   = 629,
            INDIRECT_ADDRESS_55_L   = 630,
            INDIRECT_ADDRESS_55_H   = 631,
            INDIRECT_ADDRESS_56_L   = 632,
            INDIRECT_ADDRESS_56_H   = 633,
            INDIRECT_DATA_29        = 634,
            INDIRECT_DATA_30        = 635,
            INDIRECT_DATA_31        = 636,
            INDIRECT_DATA_32        = 637,
            INDIRECT_DATA_33        = 638,
            INDIRECT_DATA_34        = 639,
            INDIRECT_DATA_35        = 640,
            INDIRECT_DATA_36        = 641,
            INDIRECT_DATA_37        = 642,
            INDIRECT_DATA_38        = 643,
            INDIRECT_DATA_39        = 644,
            INDIRECT_DATA_40        = 645,
            INDIRECT_DATA_41        = 646,
            INDIRECT_DATA_42        = 647,
            INDIRECT_DATA_43        = 648,
            INDIRECT_DATA_44        = 649,
            INDIRECT_DATA_45        = 650,
            INDIRECT_DATA_46        = 651,
            INDIRECT_DATA_47        = 652,
            INDIRECT_DATA_48        = 653,
            INDIRECT_DATA_49        = 654,
            INDIRECT_DATA_50        = 655,
            INDIRECT_DATA_51        = 656,
            INDIRECT_DATA_52        = 657,
            INDIRECT_DATA_53        = 658,
            INDIRECT_DATA_54        = 659,
            INDIRECT_DATA_55        = 660,
            INDIRECT_DATA_56        = 661
        };
    };
}  // namespace module::platform::OpenCR

#endif  // MODULE_PLATFORM_OPENCR_SERVOS_HPP
