#!/usr/bin/env bash

# Run `yarn ...` on `./docker yarn ...`
if [ "$1" == "yarn" ]; then
    shift 1
    docker-compose run \
        -p 3000:3000 \
        -p 9090:9090 \
        nusight \
        yarn "$@"

# Open a bash shell in the container on `./docker shell`
elif [ "$1" == "shell" ]; then
    shift 1
    docker-compose run \
        -p 3000:3000 \
        -p 9090:9090 \
        nusight \
        bash

# Otherwise show usage information
else
    echo "usage:"
    echo "./docker yarn [command]   # run the given yarn command in a docker container"
    echo "./docker shell            # open a bash shell in a docker container"
fi
