#!/bin/bash

# Exit immediatly on error
set -e

# Work out what kind of compression the URL uses
# And get our file
if [[ "$1" == *gz ]] # Gzip
then
    curl -L $1 | tar xz

elif [[ "$1" == *.bz2 ]] # Bzip2
then
    curl -L $1 | tar xj

elif [[ "$1" == *.zip ]] # Zip
then
    curl -L $1 -o "source.zip"
    unzip "source.zip"
    rm -rf "source.zip"
fi

# Discard our URL argument
shift 1

# Work out our context
BASE_DIR=$(pwd)
CODE_DIR=$(ls -d */)
cd "$CODE_DIR$CODE_PATH"

# Set our fags and run configure
CFLAGS="$COMPILER_FLAGS -I$TOOLCHAIN_PATH/include -O3" \
CXXFLAGS="$COMPILER_FLAGS -I$TOOLCHAIN_PATH/include -O3" \
LDFLAGS="-L$TOOLCHAIN_PATH/lib" \
./configure \
    $@ \
    --prefix="$TOOLCHAIN_PATH"

# Make and install
make -j$(nproc)
make install

# Delete our source code
rm -rf "$BASE_DIR/$CODE_DIR"
