#!/bin/bash

# Exit immediatly on error
set -e

# Work out what kind of compression the URL uses
if [[ "$1" == *gz ]]
then
    COMPRESSION=z

elif [[ "$1" == *.bz2 ]]
then
    COMPRESSION=j
fi

# Download and extract our code
curl -L $1 | tar x$COMPRESSION

# Discard our URL argument
shift 1

# Work out our context
BASE_DIR=$(pwd)
CODE_DIR=$(ls -d */)
cd "$CODE_DIR$CODE_PATH"

# Run cmake to build our makefile
cmake \
    -DCMAKE_C_FLAGS="$COMPILER_FLAGS -O3" \
    -DCMAKE_CXX_FLAGS="$COMPILER_FLAGS -O3" \
    -DCMAKE_INSTALL_PREFIX="$TOOLCHAIN_PATH" \
    $@

# Make and install
make -j$(nproc)
make install

# Delete our source code
rm -rf "$BASE_DIR/$CODE_DIR"
