#!/bin/sh

help(){
  echo "Usage: docker <subcommand>"
  echo "Commands: "
  echo "  up - Prepares the docker container. Generally only needs to be called when dependencies change."
  echo "  build - Compiles and links the NUbots codebase into the build directory"
  echo "  ssh - Get an interactive shell with the docker container"
  echo ""
}

compile(){
  mkdir -p build
  cd build
  cmake .. -GNinja
  ninja -j30
  cd ..
}

case "$1" in
  "" | "-h" | "--help")
    help
    ;;
  build)
    current_path="$(pwd)"
    docker run -t -P=false -v $current_path:/nubots/NUbots nubots/nubots ./docker compile
    ;;
  ssh)
    current_path="$(pwd)"
    docker run -t -i -P=false -v "$current_path:/nubots/NUbots" nubots/nubots /bin/bash
    ;;
  up)
    docker build -t="nubots/nubots" .
    ;;
  compile)
    compile
    ;;
  *)
    help
    exit 1
esac

