[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
known_first_party = ['b', 'utility']

[project]
name = "Horus"
version = "0.0.1"
requires-python = ">=3.10,<3.13"

dependencies = [
    # Basically required standard libraries
    "numpy",
    "termcolor",
    "tqdm",
    "ruamel.yaml",
    "pytimeparse",
    # Formatting
    "pyproj",
    "black",
    "isort",
    "pygit2",
    "cmakelang",
    # Testing/Linting
    "pytest",
    "pytest-cov",
    "pylint",
    # C++ Coverage
    "gcovr",
    # Python NUClear Modules
    "pybind11",
    # Protobuf/Neutron/NBS
    "protoc-exe",
    "xxhash",
    "stringcase",
    "protoc-wheel-0",
    "protobuf",
    "pycryptodomex",
    "natsort",
    "jsonschema",
    # Image Processing
    "Pillow",
    "opencv-contrib-python-headless",
    # Machine Learning
    "tensorflow",
    # Optimisation
    "optuna"
]
