/* This file was automatically generated by CasADi 3.8.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) modelled_mpc_walk_path_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {15, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {175, 1, 1};

/* modelled_mpc_walk_path_dyn_disc_phi_fun:(i0[15],i1[3],i2[175])->(o0[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55;
  a00=arg[0]? arg[0][0] : 0;
  a01=2.0000000000000000e-02;
  a02=arg[0]? arg[0][2] : 0;
  a03=arg[0]? arg[0][9] : 0;
  a04=arg[0]? arg[0][10] : 0;
  a05=(a03+a04);
  a06=arg[0]? arg[0][11] : 0;
  a05=(a05+a06);
  a05=(a01*a05);
  a07=2.;
  a08=(a05/a07);
  a08=(a02+a08);
  a09=cos(a08);
  a10=arg[0]? arg[0][3] : 0;
  a11=arg[0]? arg[0][4] : 0;
  a12=(a10+a11);
  a13=arg[0]? arg[0][5] : 0;
  a12=(a12+a13);
  a14=(a09*a12);
  a08=sin(a08);
  a15=arg[0]? arg[0][6] : 0;
  a16=arg[0]? arg[0][7] : 0;
  a17=(a15+a16);
  a18=arg[0]? arg[0][8] : 0;
  a17=(a17+a18);
  a19=(a08*a17);
  a14=(a14-a19);
  a14=(a01*a14);
  a00=(a00+a14);
  a02=(a02+a05);
  a05=arg[2]? arg[2][128] : 0;
  a03=(a05*a03);
  a14=arg[2]? arg[2][127] : 0;
  a19=arg[2]? arg[2][129] : 0;
  a20=arg[0]? arg[0][12] : 0;
  a21=1.0000000000000001e-01;
  a22=arg[1]? arg[1][0] : 0;
  a22=(a21*a22);
  a20=(a20+a22);
  a19=(a19*a20);
  a22=arg[2]? arg[2][130] : 0;
  a19=(a19+a22);
  a22=arg[2]? arg[2][131] : 0;
  a23=arg[2]? arg[2][137] : 0;
  a23=(a20+a23);
  a23=casadi_sq(a23);
  a24=arg[2]? arg[2][28] : 0;
  a24=casadi_sq(a24);
  a23=(a23+a24);
  a23=sqrt(a23);
  a22=(a22*a23);
  a23=arg[2]? arg[2][132] : 0;
  a25=arg[2]? arg[2][138] : 0;
  a25=(a20+a25);
  a25=casadi_sq(a25);
  a25=(a25+a24);
  a25=sqrt(a25);
  a23=(a23*a25);
  a22=(a22+a23);
  a23=arg[2]? arg[2][133] : 0;
  a25=arg[2]? arg[2][139] : 0;
  a25=(a20+a25);
  a25=casadi_sq(a25);
  a25=(a25+a24);
  a25=sqrt(a25);
  a23=(a23*a25);
  a22=(a22+a23);
  a23=arg[2]? arg[2][134] : 0;
  a25=arg[2]? arg[2][140] : 0;
  a25=(a20+a25);
  a25=casadi_sq(a25);
  a25=(a25+a24);
  a25=sqrt(a25);
  a23=(a23*a25);
  a22=(a22+a23);
  a23=arg[2]? arg[2][135] : 0;
  a25=arg[2]? arg[2][141] : 0;
  a25=(a20+a25);
  a25=casadi_sq(a25);
  a25=(a25+a24);
  a25=sqrt(a25);
  a23=(a23*a25);
  a22=(a22+a23);
  a23=arg[2]? arg[2][136] : 0;
  a25=arg[2]? arg[2][142] : 0;
  a25=(a20+a25);
  a25=casadi_sq(a25);
  a25=(a25+a24);
  a25=sqrt(a25);
  a23=(a23*a25);
  a22=(a22+a23);
  a19=(a19+a22);
  a14=(a14*a19);
  a03=(a03+a14);
  a19=arg[2]? arg[2][144] : 0;
  a04=(a19*a04);
  a22=arg[2]? arg[2][143] : 0;
  a23=arg[2]? arg[2][145] : 0;
  a25=arg[0]? arg[0][13] : 0;
  a26=arg[1]? arg[1][1] : 0;
  a26=(a21*a26);
  a25=(a25+a26);
  a23=(a23*a25);
  a26=arg[2]? arg[2][146] : 0;
  a23=(a23+a26);
  a26=arg[2]? arg[2][147] : 0;
  a27=arg[2]? arg[2][153] : 0;
  a27=(a25+a27);
  a27=casadi_sq(a27);
  a28=arg[2]? arg[2][29] : 0;
  a28=casadi_sq(a28);
  a27=(a27+a28);
  a27=sqrt(a27);
  a26=(a26*a27);
  a27=arg[2]? arg[2][148] : 0;
  a29=arg[2]? arg[2][154] : 0;
  a29=(a25+a29);
  a29=casadi_sq(a29);
  a29=(a29+a28);
  a29=sqrt(a29);
  a27=(a27*a29);
  a26=(a26+a27);
  a27=arg[2]? arg[2][149] : 0;
  a29=arg[2]? arg[2][155] : 0;
  a29=(a25+a29);
  a29=casadi_sq(a29);
  a29=(a29+a28);
  a29=sqrt(a29);
  a27=(a27*a29);
  a26=(a26+a27);
  a27=arg[2]? arg[2][150] : 0;
  a29=arg[2]? arg[2][156] : 0;
  a29=(a25+a29);
  a29=casadi_sq(a29);
  a29=(a29+a28);
  a29=sqrt(a29);
  a27=(a27*a29);
  a26=(a26+a27);
  a27=arg[2]? arg[2][151] : 0;
  a29=arg[2]? arg[2][157] : 0;
  a29=(a25+a29);
  a29=casadi_sq(a29);
  a29=(a29+a28);
  a29=sqrt(a29);
  a27=(a27*a29);
  a26=(a26+a27);
  a27=arg[2]? arg[2][152] : 0;
  a29=arg[2]? arg[2][158] : 0;
  a29=(a25+a29);
  a29=casadi_sq(a29);
  a29=(a29+a28);
  a29=sqrt(a29);
  a27=(a27*a29);
  a26=(a26+a27);
  a23=(a23+a26);
  a22=(a22*a23);
  a04=(a04+a22);
  a23=(a03+a04);
  a26=arg[2]? arg[2][160] : 0;
  a06=(a26*a06);
  a27=arg[2]? arg[2][159] : 0;
  a29=arg[2]? arg[2][161] : 0;
  a30=arg[0]? arg[0][14] : 0;
  a31=arg[1]? arg[1][2] : 0;
  a21=(a21*a31);
  a30=(a30+a21);
  a29=(a29*a30);
  a21=arg[2]? arg[2][162] : 0;
  a29=(a29+a21);
  a21=arg[2]? arg[2][163] : 0;
  a31=arg[2]? arg[2][169] : 0;
  a31=(a30+a31);
  a31=casadi_sq(a31);
  a32=arg[2]? arg[2][30] : 0;
  a32=casadi_sq(a32);
  a31=(a31+a32);
  a31=sqrt(a31);
  a21=(a21*a31);
  a31=arg[2]? arg[2][164] : 0;
  a33=arg[2]? arg[2][170] : 0;
  a33=(a30+a33);
  a33=casadi_sq(a33);
  a33=(a33+a32);
  a33=sqrt(a33);
  a31=(a31*a33);
  a21=(a21+a31);
  a31=arg[2]? arg[2][165] : 0;
  a33=arg[2]? arg[2][171] : 0;
  a33=(a30+a33);
  a33=casadi_sq(a33);
  a33=(a33+a32);
  a33=sqrt(a33);
  a31=(a31*a33);
  a21=(a21+a31);
  a31=arg[2]? arg[2][166] : 0;
  a33=arg[2]? arg[2][172] : 0;
  a33=(a30+a33);
  a33=casadi_sq(a33);
  a33=(a33+a32);
  a33=sqrt(a33);
  a31=(a31*a33);
  a21=(a21+a31);
  a31=arg[2]? arg[2][167] : 0;
  a33=arg[2]? arg[2][173] : 0;
  a33=(a30+a33);
  a33=casadi_sq(a33);
  a33=(a33+a32);
  a33=sqrt(a33);
  a31=(a31*a33);
  a21=(a21+a31);
  a31=arg[2]? arg[2][168] : 0;
  a33=arg[2]? arg[2][174] : 0;
  a33=(a30+a33);
  a33=casadi_sq(a33);
  a33=(a33+a32);
  a33=sqrt(a33);
  a31=(a31*a33);
  a21=(a21+a31);
  a29=(a29+a21);
  a27=(a27*a29);
  a06=(a06+a27);
  a23=(a23+a06);
  a23=(a01*a23);
  a29=(a23/a07);
  a29=(a02+a29);
  a21=cos(a29);
  a31=arg[2]? arg[2][32] : 0;
  a10=(a31*a10);
  a33=arg[2]? arg[2][31] : 0;
  a34=arg[2]? arg[2][33] : 0;
  a34=(a34*a20);
  a35=arg[2]? arg[2][34] : 0;
  a34=(a34+a35);
  a35=arg[2]? arg[2][35] : 0;
  a36=arg[2]? arg[2][41] : 0;
  a36=(a20+a36);
  a36=casadi_sq(a36);
  a36=(a36+a24);
  a36=sqrt(a36);
  a35=(a35*a36);
  a36=arg[2]? arg[2][36] : 0;
  a37=arg[2]? arg[2][42] : 0;
  a37=(a20+a37);
  a37=casadi_sq(a37);
  a37=(a37+a24);
  a37=sqrt(a37);
  a36=(a36*a37);
  a35=(a35+a36);
  a36=arg[2]? arg[2][37] : 0;
  a37=arg[2]? arg[2][43] : 0;
  a37=(a20+a37);
  a37=casadi_sq(a37);
  a37=(a37+a24);
  a37=sqrt(a37);
  a36=(a36*a37);
  a35=(a35+a36);
  a36=arg[2]? arg[2][38] : 0;
  a37=arg[2]? arg[2][44] : 0;
  a37=(a20+a37);
  a37=casadi_sq(a37);
  a37=(a37+a24);
  a37=sqrt(a37);
  a36=(a36*a37);
  a35=(a35+a36);
  a36=arg[2]? arg[2][39] : 0;
  a37=arg[2]? arg[2][45] : 0;
  a37=(a20+a37);
  a37=casadi_sq(a37);
  a37=(a37+a24);
  a37=sqrt(a37);
  a36=(a36*a37);
  a35=(a35+a36);
  a36=arg[2]? arg[2][40] : 0;
  a37=arg[2]? arg[2][46] : 0;
  a37=(a20+a37);
  a37=casadi_sq(a37);
  a37=(a37+a24);
  a37=sqrt(a37);
  a36=(a36*a37);
  a35=(a35+a36);
  a34=(a34+a35);
  a33=(a33*a34);
  a10=(a10+a33);
  a34=arg[2]? arg[2][48] : 0;
  a11=(a34*a11);
  a35=arg[2]? arg[2][47] : 0;
  a36=arg[2]? arg[2][49] : 0;
  a36=(a36*a25);
  a37=arg[2]? arg[2][50] : 0;
  a36=(a36+a37);
  a37=arg[2]? arg[2][51] : 0;
  a38=arg[2]? arg[2][57] : 0;
  a38=(a25+a38);
  a38=casadi_sq(a38);
  a38=(a38+a28);
  a38=sqrt(a38);
  a37=(a37*a38);
  a38=arg[2]? arg[2][52] : 0;
  a39=arg[2]? arg[2][58] : 0;
  a39=(a25+a39);
  a39=casadi_sq(a39);
  a39=(a39+a28);
  a39=sqrt(a39);
  a38=(a38*a39);
  a37=(a37+a38);
  a38=arg[2]? arg[2][53] : 0;
  a39=arg[2]? arg[2][59] : 0;
  a39=(a25+a39);
  a39=casadi_sq(a39);
  a39=(a39+a28);
  a39=sqrt(a39);
  a38=(a38*a39);
  a37=(a37+a38);
  a38=arg[2]? arg[2][54] : 0;
  a39=arg[2]? arg[2][60] : 0;
  a39=(a25+a39);
  a39=casadi_sq(a39);
  a39=(a39+a28);
  a39=sqrt(a39);
  a38=(a38*a39);
  a37=(a37+a38);
  a38=arg[2]? arg[2][55] : 0;
  a39=arg[2]? arg[2][61] : 0;
  a39=(a25+a39);
  a39=casadi_sq(a39);
  a39=(a39+a28);
  a39=sqrt(a39);
  a38=(a38*a39);
  a37=(a37+a38);
  a38=arg[2]? arg[2][56] : 0;
  a39=arg[2]? arg[2][62] : 0;
  a39=(a25+a39);
  a39=casadi_sq(a39);
  a39=(a39+a28);
  a39=sqrt(a39);
  a38=(a38*a39);
  a37=(a37+a38);
  a36=(a36+a37);
  a35=(a35*a36);
  a11=(a11+a35);
  a36=(a10+a11);
  a37=arg[2]? arg[2][64] : 0;
  a13=(a37*a13);
  a38=arg[2]? arg[2][63] : 0;
  a39=arg[2]? arg[2][65] : 0;
  a39=(a39*a30);
  a40=arg[2]? arg[2][66] : 0;
  a39=(a39+a40);
  a40=arg[2]? arg[2][67] : 0;
  a41=arg[2]? arg[2][73] : 0;
  a41=(a30+a41);
  a41=casadi_sq(a41);
  a41=(a41+a32);
  a41=sqrt(a41);
  a40=(a40*a41);
  a41=arg[2]? arg[2][68] : 0;
  a42=arg[2]? arg[2][74] : 0;
  a42=(a30+a42);
  a42=casadi_sq(a42);
  a42=(a42+a32);
  a42=sqrt(a42);
  a41=(a41*a42);
  a40=(a40+a41);
  a41=arg[2]? arg[2][69] : 0;
  a42=arg[2]? arg[2][75] : 0;
  a42=(a30+a42);
  a42=casadi_sq(a42);
  a42=(a42+a32);
  a42=sqrt(a42);
  a41=(a41*a42);
  a40=(a40+a41);
  a41=arg[2]? arg[2][70] : 0;
  a42=arg[2]? arg[2][76] : 0;
  a42=(a30+a42);
  a42=casadi_sq(a42);
  a42=(a42+a32);
  a42=sqrt(a42);
  a41=(a41*a42);
  a40=(a40+a41);
  a41=arg[2]? arg[2][71] : 0;
  a42=arg[2]? arg[2][77] : 0;
  a42=(a30+a42);
  a42=casadi_sq(a42);
  a42=(a42+a32);
  a42=sqrt(a42);
  a41=(a41*a42);
  a40=(a40+a41);
  a41=arg[2]? arg[2][72] : 0;
  a42=arg[2]? arg[2][78] : 0;
  a42=(a30+a42);
  a42=casadi_sq(a42);
  a42=(a42+a32);
  a42=sqrt(a42);
  a41=(a41*a42);
  a40=(a40+a41);
  a39=(a39+a40);
  a38=(a38*a39);
  a13=(a13+a38);
  a36=(a36+a13);
  a39=(a21*a36);
  a29=sin(a29);
  a40=arg[2]? arg[2][80] : 0;
  a15=(a40*a15);
  a41=arg[2]? arg[2][79] : 0;
  a42=arg[2]? arg[2][81] : 0;
  a42=(a42*a20);
  a43=arg[2]? arg[2][82] : 0;
  a42=(a42+a43);
  a43=arg[2]? arg[2][83] : 0;
  a44=arg[2]? arg[2][89] : 0;
  a44=(a20+a44);
  a44=casadi_sq(a44);
  a44=(a44+a24);
  a44=sqrt(a44);
  a43=(a43*a44);
  a44=arg[2]? arg[2][84] : 0;
  a45=arg[2]? arg[2][90] : 0;
  a45=(a20+a45);
  a45=casadi_sq(a45);
  a45=(a45+a24);
  a45=sqrt(a45);
  a44=(a44*a45);
  a43=(a43+a44);
  a44=arg[2]? arg[2][85] : 0;
  a45=arg[2]? arg[2][91] : 0;
  a45=(a20+a45);
  a45=casadi_sq(a45);
  a45=(a45+a24);
  a45=sqrt(a45);
  a44=(a44*a45);
  a43=(a43+a44);
  a44=arg[2]? arg[2][86] : 0;
  a45=arg[2]? arg[2][92] : 0;
  a45=(a20+a45);
  a45=casadi_sq(a45);
  a45=(a45+a24);
  a45=sqrt(a45);
  a44=(a44*a45);
  a43=(a43+a44);
  a44=arg[2]? arg[2][87] : 0;
  a45=arg[2]? arg[2][93] : 0;
  a45=(a20+a45);
  a45=casadi_sq(a45);
  a45=(a45+a24);
  a45=sqrt(a45);
  a44=(a44*a45);
  a43=(a43+a44);
  a44=arg[2]? arg[2][88] : 0;
  a45=arg[2]? arg[2][94] : 0;
  a45=(a20+a45);
  a45=casadi_sq(a45);
  a45=(a45+a24);
  a45=sqrt(a45);
  a44=(a44*a45);
  a43=(a43+a44);
  a42=(a42+a43);
  a41=(a41*a42);
  a15=(a15+a41);
  a42=arg[2]? arg[2][96] : 0;
  a16=(a42*a16);
  a43=arg[2]? arg[2][95] : 0;
  a44=arg[2]? arg[2][97] : 0;
  a44=(a44*a25);
  a45=arg[2]? arg[2][98] : 0;
  a44=(a44+a45);
  a45=arg[2]? arg[2][99] : 0;
  a24=arg[2]? arg[2][105] : 0;
  a24=(a25+a24);
  a24=casadi_sq(a24);
  a24=(a24+a28);
  a24=sqrt(a24);
  a45=(a45*a24);
  a24=arg[2]? arg[2][100] : 0;
  a46=arg[2]? arg[2][106] : 0;
  a46=(a25+a46);
  a46=casadi_sq(a46);
  a46=(a46+a28);
  a46=sqrt(a46);
  a24=(a24*a46);
  a45=(a45+a24);
  a24=arg[2]? arg[2][101] : 0;
  a46=arg[2]? arg[2][107] : 0;
  a46=(a25+a46);
  a46=casadi_sq(a46);
  a46=(a46+a28);
  a46=sqrt(a46);
  a24=(a24*a46);
  a45=(a45+a24);
  a24=arg[2]? arg[2][102] : 0;
  a46=arg[2]? arg[2][108] : 0;
  a46=(a25+a46);
  a46=casadi_sq(a46);
  a46=(a46+a28);
  a46=sqrt(a46);
  a24=(a24*a46);
  a45=(a45+a24);
  a24=arg[2]? arg[2][103] : 0;
  a46=arg[2]? arg[2][109] : 0;
  a46=(a25+a46);
  a46=casadi_sq(a46);
  a46=(a46+a28);
  a46=sqrt(a46);
  a24=(a24*a46);
  a45=(a45+a24);
  a24=arg[2]? arg[2][104] : 0;
  a46=arg[2]? arg[2][110] : 0;
  a46=(a25+a46);
  a46=casadi_sq(a46);
  a46=(a46+a28);
  a46=sqrt(a46);
  a24=(a24*a46);
  a45=(a45+a24);
  a44=(a44+a45);
  a43=(a43*a44);
  a16=(a16+a43);
  a44=(a15+a16);
  a45=arg[2]? arg[2][112] : 0;
  a18=(a45*a18);
  a24=arg[2]? arg[2][111] : 0;
  a46=arg[2]? arg[2][113] : 0;
  a46=(a46*a30);
  a28=arg[2]? arg[2][114] : 0;
  a46=(a46+a28);
  a28=arg[2]? arg[2][115] : 0;
  a47=arg[2]? arg[2][121] : 0;
  a47=(a30+a47);
  a47=casadi_sq(a47);
  a47=(a47+a32);
  a47=sqrt(a47);
  a28=(a28*a47);
  a47=arg[2]? arg[2][116] : 0;
  a48=arg[2]? arg[2][122] : 0;
  a48=(a30+a48);
  a48=casadi_sq(a48);
  a48=(a48+a32);
  a48=sqrt(a48);
  a47=(a47*a48);
  a28=(a28+a47);
  a47=arg[2]? arg[2][117] : 0;
  a48=arg[2]? arg[2][123] : 0;
  a48=(a30+a48);
  a48=casadi_sq(a48);
  a48=(a48+a32);
  a48=sqrt(a48);
  a47=(a47*a48);
  a28=(a28+a47);
  a47=arg[2]? arg[2][118] : 0;
  a48=arg[2]? arg[2][124] : 0;
  a48=(a30+a48);
  a48=casadi_sq(a48);
  a48=(a48+a32);
  a48=sqrt(a48);
  a47=(a47*a48);
  a28=(a28+a47);
  a47=arg[2]? arg[2][119] : 0;
  a48=arg[2]? arg[2][125] : 0;
  a48=(a30+a48);
  a48=casadi_sq(a48);
  a48=(a48+a32);
  a48=sqrt(a48);
  a47=(a47*a48);
  a28=(a28+a47);
  a47=arg[2]? arg[2][120] : 0;
  a48=arg[2]? arg[2][126] : 0;
  a48=(a30+a48);
  a48=casadi_sq(a48);
  a48=(a48+a32);
  a48=sqrt(a48);
  a47=(a47*a48);
  a28=(a28+a47);
  a46=(a46+a28);
  a24=(a24*a46);
  a18=(a18+a24);
  a44=(a44+a18);
  a46=(a29*a44);
  a39=(a39-a46);
  a39=(a01*a39);
  a00=(a00+a39);
  a02=(a02+a23);
  a03=(a05*a03);
  a03=(a03+a14);
  a04=(a19*a04);
  a04=(a04+a22);
  a23=(a03+a04);
  a06=(a26*a06);
  a06=(a06+a27);
  a23=(a23+a06);
  a23=(a01*a23);
  a39=(a23/a07);
  a39=(a02+a39);
  a46=cos(a39);
  a10=(a31*a10);
  a10=(a10+a33);
  a11=(a34*a11);
  a11=(a11+a35);
  a28=(a10+a11);
  a13=(a37*a13);
  a13=(a13+a38);
  a28=(a28+a13);
  a47=(a46*a28);
  a39=sin(a39);
  a15=(a40*a15);
  a15=(a15+a41);
  a16=(a42*a16);
  a16=(a16+a43);
  a48=(a15+a16);
  a18=(a45*a18);
  a18=(a18+a24);
  a48=(a48+a18);
  a32=(a39*a48);
  a47=(a47-a32);
  a47=(a01*a47);
  a00=(a00+a47);
  a02=(a02+a23);
  a03=(a05*a03);
  a03=(a03+a14);
  a04=(a19*a04);
  a04=(a04+a22);
  a23=(a03+a04);
  a06=(a26*a06);
  a06=(a06+a27);
  a23=(a23+a06);
  a23=(a01*a23);
  a47=(a23/a07);
  a47=(a02+a47);
  a32=cos(a47);
  a10=(a31*a10);
  a10=(a10+a33);
  a11=(a34*a11);
  a11=(a11+a35);
  a49=(a10+a11);
  a13=(a37*a13);
  a13=(a13+a38);
  a49=(a49+a13);
  a50=(a32*a49);
  a47=sin(a47);
  a15=(a40*a15);
  a15=(a15+a41);
  a16=(a42*a16);
  a16=(a16+a43);
  a51=(a15+a16);
  a18=(a45*a18);
  a18=(a18+a24);
  a51=(a51+a18);
  a52=(a47*a51);
  a50=(a50-a52);
  a50=(a01*a50);
  a00=(a00+a50);
  a02=(a02+a23);
  a03=(a05*a03);
  a03=(a03+a14);
  a04=(a19*a04);
  a04=(a04+a22);
  a23=(a03+a04);
  a06=(a26*a06);
  a06=(a06+a27);
  a23=(a23+a06);
  a23=(a01*a23);
  a07=(a23/a07);
  a07=(a02+a07);
  a50=cos(a07);
  a10=(a31*a10);
  a10=(a10+a33);
  a11=(a34*a11);
  a11=(a11+a35);
  a52=(a10+a11);
  a13=(a37*a13);
  a13=(a13+a38);
  a52=(a52+a13);
  a53=(a50*a52);
  a07=sin(a07);
  a15=(a40*a15);
  a15=(a15+a41);
  a16=(a42*a16);
  a16=(a16+a43);
  a54=(a15+a16);
  a18=(a45*a18);
  a18=(a18+a24);
  a54=(a54+a18);
  a55=(a07*a54);
  a53=(a53-a55);
  a53=(a01*a53);
  a00=(a00+a53);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a08=(a08*a12);
  a09=(a09*a17);
  a08=(a08+a09);
  a08=(a01*a08);
  a00=(a00+a08);
  a29=(a29*a36);
  a21=(a21*a44);
  a29=(a29+a21);
  a29=(a01*a29);
  a00=(a00+a29);
  a39=(a39*a28);
  a46=(a46*a48);
  a39=(a39+a46);
  a39=(a01*a39);
  a00=(a00+a39);
  a47=(a47*a49);
  a32=(a32*a51);
  a47=(a47+a32);
  a47=(a01*a47);
  a00=(a00+a47);
  a07=(a07*a52);
  a50=(a50*a54);
  a07=(a07+a50);
  a01=(a01*a07);
  a00=(a00+a01);
  if (res[0]!=0) res[0][1]=a00;
  a02=(a02+a23);
  if (res[0]!=0) res[0][2]=a02;
  a31=(a31*a10);
  a31=(a31+a33);
  if (res[0]!=0) res[0][3]=a31;
  a34=(a34*a11);
  a34=(a34+a35);
  if (res[0]!=0) res[0][4]=a34;
  a37=(a37*a13);
  a37=(a37+a38);
  if (res[0]!=0) res[0][5]=a37;
  a40=(a40*a15);
  a40=(a40+a41);
  if (res[0]!=0) res[0][6]=a40;
  a42=(a42*a16);
  a42=(a42+a43);
  if (res[0]!=0) res[0][7]=a42;
  a45=(a45*a18);
  a45=(a45+a24);
  if (res[0]!=0) res[0][8]=a45;
  a05=(a05*a03);
  a05=(a05+a14);
  if (res[0]!=0) res[0][9]=a05;
  a19=(a19*a04);
  a19=(a19+a22);
  if (res[0]!=0) res[0][10]=a19;
  a26=(a26*a06);
  a26=(a26+a27);
  if (res[0]!=0) res[0][11]=a26;
  if (res[0]!=0) res[0][12]=a20;
  if (res[0]!=0) res[0][13]=a25;
  if (res[0]!=0) res[0][14]=a30;
  return 0;
}

CASADI_SYMBOL_EXPORT int modelled_mpc_walk_path_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int modelled_mpc_walk_path_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void modelled_mpc_walk_path_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void modelled_mpc_walk_path_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void modelled_mpc_walk_path_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int modelled_mpc_walk_path_dyn_disc_phi_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int modelled_mpc_walk_path_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real modelled_mpc_walk_path_dyn_disc_phi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* modelled_mpc_walk_path_dyn_disc_phi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* modelled_mpc_walk_path_dyn_disc_phi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* modelled_mpc_walk_path_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* modelled_mpc_walk_path_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int modelled_mpc_walk_path_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int modelled_mpc_walk_path_dyn_disc_phi_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
