#!/bin/sh
set -e
src_dir=$1

# Get configuration details from abuild
source /etc/abuild.conf

# Go to the APKBUILD folder and build
cd "${src_dir}"
abuild

# Find the resulting packages and install it
find "${REPODEST}" -name "*.apk" -exec sudo apk add --no-cache --allow-untrusted {} \;

# Cleanup by deleting the entire temp directory
sudo rm -rf "${REPODEST}" "${SRCDEST}"
