- duration: 500
  targets:
    - id: R_SHOULDER_PITCH
      position: 2.05450177
      gain: 10
      torque: 100
    - id: L_SHOULDER_PITCH
      position: 2.05143309
      gain: 10
      torque: 100
    - id: R_SHOULDER_ROLL
      position: -0.176259071
      gain: 10
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.176259071
      gain: 10
      torque: 100
    - id: R_ELBOW
      position: -1.56657684
      gain: 10
      torque: 100
    - id: L_ELBOW
      position: -1.56811118
      gain: 10
      torque: 100
    - id: R_HIP_YAW
      position: 0.00460306602
      gain: 10
      torque: 100
    - id: L_HIP_YAW
      position: 0.0214809757
      gain: 10
      torque: 100
    - id: R_HIP_ROLL
      position: -0.0997330993
      gain: 10
      torque: 100
    - id: L_HIP_ROLL
      position: 0.0874582604
      gain: 10
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0.147298113
      gain: 10
      torque: 100
    - id: L_ANKLE_ROLL
      position: -0.139626339
      gain: 10
      torque: 100
    - id: HEAD_PITCH
      position: -0.135023281
      gain: 10
      torque: 100
    - id: HEAD_YAW
      position: -0.118145362
      gain: 10
      torque: 100
    - id: R_HIP_PITCH
      position: -0.273688763
      gain: 10
      torque: 100
    - id: L_HIP_PITCH
      position: -0.264482647
      gain: 10
      torque: 100
    - id: R_KNEE
      position: 0.565550268
      gain: 10
      torque: 100
    - id: L_KNEE
      position: 0.605443478
      gain: 10
      torque: 100
    - id: R_ANKLE_PITCH
      position: -0.364222586
      gain: 10
      torque: 100
    - id: L_ANKLE_PITCH
      position: -0.413321942
      gain: 10
      torque: 100
- duration: 500
  targets:
    - id: R_SHOULDER_ROLL
      position: -0.176259071
      gain: 10
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.176259071
      gain: 10
      torque: 100
    - id: R_HIP_YAW
      position: 0.00460306602
      gain: 10
      torque: 100
    - id: L_HIP_YAW
      position: 0.0214809757
      gain: 10
      torque: 100
    - id: R_HIP_ROLL
      position: -0.0997330993
      gain: 10
      torque: 100
    - id: L_HIP_ROLL
      position: 0.0874582604
      gain: 10
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0.147298113
      gain: 10
      torque: 100
    - id: L_ANKLE_ROLL
      position: -0.139626339
      gain: 10
      torque: 100
    - id: HEAD_PITCH
      position: -0.135023281
      gain: 10
      torque: 100
    - id: HEAD_YAW
      position: -0.118145362
      gain: 10
      torque: 100
    - id: R_HIP_PITCH
      position: -0.273688763
      gain: 10
      torque: 100
    - id: L_HIP_PITCH
      position: -0.264482647
      gain: 10
      torque: 100
    - id: R_KNEE
      position: 0.565550268
      gain: 10
      torque: 100
    - id: L_KNEE
      position: 0.605443478
      gain: 10
      torque: 100
    - id: R_ANKLE_PITCH
      position: -0.364222586
      gain: 10
      torque: 100
    - id: L_ANKLE_PITCH
      position: -0.413321942
      gain: 10
      torque: 100
    - id: L_SHOULDER_PITCH
      position: -1.03722429
      gain: 10
      torque: 100
    - id: R_SHOULDER_PITCH
      position: -0.962040842
      gain: 10
      torque: 100
    - id: L_ELBOW
      position: -0.115076654
      gain: 10
      torque: 100
    - id: R_ELBOW
      position: -0.242428154
      gain: 10
      torque: 100
- duration: 1000
  targets:
    - id: R_SHOULDER_ROLL
      position: -0.176259071
      gain: 10
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.176259071
      gain: 10
      torque: 100
    - id: R_HIP_YAW
      position: 0.00460306602
      gain: 10
      torque: 100
    - id: R_HIP_ROLL
      position: -0.0997330993
      gain: 10
      torque: 100
    - id: HEAD_PITCH
      position: -0.135023281
      gain: 10
      torque: 100
    - id: HEAD_YAW
      position: -0.118145362
      gain: 10
      torque: 100
    - id: R_HIP_PITCH
      position: -0.273688763
      gain: 10
      torque: 100
    - id: R_KNEE
      position: 0.565550268
      gain: 10
      torque: 100
    - id: R_ANKLE_PITCH
      position: -0.364222586
      gain: 10
      torque: 100
    - id: L_SHOULDER_PITCH
      position: -1.03722429
      gain: 10
      torque: 100
    - id: R_SHOULDER_PITCH
      position: -0.962040842
      gain: 10
      torque: 100
    - id: L_ELBOW
      position: -0.115076654
      gain: 10
      torque: 100
    - id: R_ELBOW
      position: -0.242428154
      gain: 10
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0.787124336
      gain: 10
      torque: 100
    - id: L_ANKLE_ROLL
      position: 0.497131139
      gain: 10
      torque: 100
    - id: L_ANKLE_PITCH
      position: -0.813788712
      gain: 10
      torque: 100
    - id: L_KNEE
      position: 1.54907203
      gain: 10
      torque: 100
    - id: L_HIP_PITCH
      position: -0.829125404
      gain: 10
      torque: 100
    - id: L_HIP_ROLL
      position: 0.0475650169
      gain: 10
      torque: 100
    - id: L_HIP_YAW
      position: -0.0981987417
      gain: 10
      torque: 100
- duration: 500
  targets:
    - id: R_SHOULDER_ROLL
      position: -0.176259071
      gain: 10
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.176259071
      gain: 10
      torque: 100
    - id: R_HIP_YAW
      position: 0.00460306602
      gain: 10
      torque: 100
    - id: R_HIP_ROLL
      position: -0.0997330993
      gain: 10
      torque: 100
    - id: HEAD_PITCH
      position: -0.135023281
      gain: 10
      torque: 100
    - id: HEAD_YAW
      position: -0.118145362
      gain: 10
      torque: 100
    - id: R_HIP_PITCH
      position: -0.273688763
      gain: 10
      torque: 100
    - id: R_KNEE
      position: 0.565550268
      gain: 10
      torque: 100
    - id: R_ANKLE_PITCH
      position: -0.364222586
      gain: 10
      torque: 100
    - id: L_SHOULDER_PITCH
      position: -1.03722429
      gain: 10
      torque: 100
    - id: R_SHOULDER_PITCH
      position: -0.962040842
      gain: 10
      torque: 100
    - id: L_ELBOW
      position: -0.115076654
      gain: 10
      torque: 100
    - id: R_ELBOW
      position: -0.242428154
      gain: 10
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0.787124336
      gain: 10
      torque: 100
    - id: L_ANKLE_ROLL
      position: 0.497131139
      gain: 10
      torque: 100
    - id: L_ANKLE_PITCH
      position: -0.813788712
      gain: 10
      torque: 100
    - id: L_KNEE
      position: 1.54907203
      gain: 10
      torque: 100
    - id: L_HIP_PITCH
      position: -0.829125404
      gain: 10
      torque: 100
    - id: L_HIP_ROLL
      position: 0.5
      gain: 10
      torque: 100
    - id: L_HIP_YAW
      position: -0.0981987417
      gain: 10
      torque: 100
