/* This file was automatically generated by CasADi 3.8.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mpc_walk_path_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {28, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {9, 1, 1};
static const casadi_int casadi_s6[29] = 
  {9, 9, 0, 2, 4, 6, 8, 10,
  11, 13, 15, 17, 0, 6, 1, 7,
  2, 8, 3, 4, 3, 4, 5, 0,
  6, 1, 7, 2, 8};
static const casadi_int casadi_s7[3] = {0, 0, 1};
static const casadi_int casadi_s8[3] = {0, 9, 1};

/* mpc_walk_path_cost_ext_cost_fun_jac_hess:(i0[6],i1[3],i2[0],i3[28])->(o0,o1[9],o2[9x9,17nz],o3[],o4[0x9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26;
  a00=arg[3]? arg[3][5] : 0;
  a01=arg[3]? arg[3][8] : 0;
  a01=casadi_sq(a01);
  a02=1.;
  a03=arg[0]? arg[0][0] : 0;
  a04=arg[3]? arg[3][0] : 0;
  a03=(a03-a04);
  a04=casadi_sq(a03);
  a05=arg[0]? arg[0][1] : 0;
  a06=arg[3]? arg[3][1] : 0;
  a05=(a05-a06);
  a06=casadi_sq(a05);
  a04=(a04+a06);
  a04=(a04/a01);
  a04=(a02+a04);
  a04=sqrt(a04);
  a06=(a04-a02);
  a06=(a01*a06);
  a06=(a00*a06);
  a07=arg[3]? arg[3][6] : 0;
  a08=arg[3]? arg[3][3] : 0;
  a07=(a07*a08);
  a09=arg[0]? arg[0][2] : 0;
  a10=arg[3]? arg[3][2] : 0;
  a10=(a09-a10);
  a11=cos(a10);
  a12=(a02-a11);
  a12=(a07*a12);
  a13=arg[3]? arg[3][7] : 0;
  a08=(a02-a08);
  a13=(a13*a08);
  a08=arg[3]? arg[3][4] : 0;
  a09=(a09-a08);
  a08=cos(a09);
  a02=(a02-a08);
  a02=(a13*a02);
  a12=(a12+a02);
  a06=(a06+a12);
  a12=arg[3]? arg[3][9] : 0;
  a02=arg[0]? arg[0][3] : 0;
  a14=1.0000000000000001e-01;
  a15=arg[1]? arg[1][0] : 0;
  a16=(a14*a15);
  a02=(a02+a16);
  a17=casadi_sq(a02);
  a17=(a12*a17);
  a18=arg[3]? arg[3][10] : 0;
  a19=arg[0]? arg[0][4] : 0;
  a20=arg[1]? arg[1][1] : 0;
  a21=(a14*a20);
  a19=(a19+a21);
  a22=casadi_sq(a19);
  a22=(a18*a22);
  a17=(a17+a22);
  a22=arg[3]? arg[3][11] : 0;
  a23=arg[0]? arg[0][5] : 0;
  a24=arg[1]? arg[1][2] : 0;
  a25=(a14*a24);
  a23=(a23+a25);
  a26=casadi_sq(a23);
  a26=(a22*a26);
  a17=(a17+a26);
  a06=(a06+a17);
  a17=arg[3]? arg[3][12] : 0;
  a16=casadi_sq(a16);
  a16=(a17*a16);
  a26=arg[3]? arg[3][13] : 0;
  a21=casadi_sq(a21);
  a21=(a26*a21);
  a16=(a16+a21);
  a21=arg[3]? arg[3][14] : 0;
  a25=casadi_sq(a25);
  a25=(a21*a25);
  a16=(a16+a25);
  a06=(a06+a16);
  if (res[0]!=0) res[0][0]=a06;
  a06=2.0000000000000001e-01;
  a15=(a06*a15);
  a15=(a15*a17);
  a15=(a14*a15);
  a02=(2.*a02);
  a02=(a02*a12);
  a16=(a14*a02);
  a15=(a15+a16);
  if (res[1]!=0) res[1][0]=a15;
  a20=(a06*a20);
  a20=(a20*a26);
  a20=(a14*a20);
  a19=(2.*a19);
  a19=(a19*a18);
  a15=(a14*a19);
  a20=(a20+a15);
  if (res[1]!=0) res[1][1]=a20;
  a24=(a06*a24);
  a24=(a24*a21);
  a24=(a14*a24);
  a23=(2.*a23);
  a23=(a23*a22);
  a14=(a14*a23);
  a24=(a24+a14);
  if (res[1]!=0) res[1][2]=a24;
  a03=(2.*a03);
  a00=(a01*a00);
  a04=(2.*a04);
  a00=(a00/a04);
  a24=(a00/a01);
  a14=(a03*a24);
  if (res[1]!=0) res[1][3]=a14;
  a05=(2.*a05);
  a14=(a05*a24);
  if (res[1]!=0) res[1][4]=a14;
  a09=sin(a09);
  a09=(a09*a13);
  a10=sin(a10);
  a10=(a10*a07);
  a09=(a09+a10);
  if (res[1]!=0) res[1][5]=a09;
  if (res[1]!=0) res[1][6]=a02;
  if (res[1]!=0) res[1][7]=a19;
  if (res[1]!=0) res[1][8]=a23;
  a23=2.0000000000000004e-02;
  a17=(a23*a17);
  a19=(a23*a12);
  a17=(a17+a19);
  if (res[2]!=0) res[2][0]=a17;
  a17=(a06*a12);
  if (res[2]!=0) res[2][1]=a17;
  a26=(a23*a26);
  a19=(a23*a18);
  a26=(a26+a19);
  if (res[2]!=0) res[2][2]=a26;
  a26=(a06*a18);
  if (res[2]!=0) res[2][3]=a26;
  a21=(a23*a21);
  a23=(a23*a22);
  a21=(a21+a23);
  if (res[2]!=0) res[2][4]=a21;
  a06=(a06*a22);
  if (res[2]!=0) res[2][5]=a06;
  a24=(2.*a24);
  a00=(a00/a04);
  a21=(a03/a01);
  a21=(a21/a04);
  a21=(2.*a21);
  a21=(a00*a21);
  a21=(a21/a01);
  a21=(a03*a21);
  a21=(a24-a21);
  if (res[2]!=0) res[2][6]=a21;
  a21=(a05/a01);
  a21=(a21/a04);
  a21=(2.*a21);
  a00=(a00*a21);
  a00=(a00/a01);
  a03=(a03*a00);
  a03=(-a03);
  if (res[2]!=0) res[2][7]=a03;
  if (res[2]!=0) res[2][8]=a03;
  a05=(a05*a00);
  a24=(a24-a05);
  if (res[2]!=0) res[2][9]=a24;
  a13=(a13*a08);
  a07=(a07*a11);
  a13=(a13+a07);
  if (res[2]!=0) res[2][10]=a13;
  if (res[2]!=0) res[2][11]=a17;
  a12=(2.*a12);
  if (res[2]!=0) res[2][12]=a12;
  if (res[2]!=0) res[2][13]=a26;
  a18=(2.*a18);
  if (res[2]!=0) res[2][14]=a18;
  if (res[2]!=0) res[2][15]=a06;
  a22=(2.*a22);
  if (res[2]!=0) res[2][16]=a22;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpc_walk_path_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mpc_walk_path_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpc_walk_path_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mpc_walk_path_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void mpc_walk_path_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mpc_walk_path_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int mpc_walk_path_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real mpc_walk_path_cost_ext_cost_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpc_walk_path_cost_ext_cost_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpc_walk_path_cost_ext_cost_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpc_walk_path_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpc_walk_path_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mpc_walk_path_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpc_walk_path_cost_ext_cost_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
