/* This file was automatically generated by CasADi 3.8.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mpc_walk_path_constr_h_e_fun_jac_uxt_zt_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};
static const casadi_int casadi_s3[3] = {28, 1, 1};
static const casadi_int casadi_s4[15] = 
  {6, 4, 0, 2, 4, 6, 8, 0,
  1, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s5[11] = 
  {6, 6, 0, 1, 2, 2, 2, 2,
  2, 0, 1};
static const casadi_int casadi_s6[3] = {4, 0, 1};
static const casadi_int casadi_s7[3] = {0, 0, 1};

/* mpc_walk_path_constr_h_e_fun_jac_uxt_zt_hess:(i0[6],i1[0],i2[4],i3[0],i4[28])->(o0[4],o1[6x4,8nz],o2[6x6,2nz],o3[4x0],o4[]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14;
  a00=arg[4]? arg[4][24] : 0;
  a01=arg[4]? arg[4][15] : 0;
  a01=casadi_sq(a01);
  a02=arg[0]? arg[0][0] : 0;
  a03=arg[4]? arg[4][16] : 0;
  a03=(a02-a03);
  a04=casadi_sq(a03);
  a05=arg[0]? arg[0][1] : 0;
  a06=arg[4]? arg[4][17] : 0;
  a06=(a05-a06);
  a07=casadi_sq(a06);
  a04=(a04+a07);
  a04=(a01-a04);
  a04=(a00*a04);
  if (res[0]!=0) res[0][0]=a04;
  a04=arg[4]? arg[4][25] : 0;
  a07=arg[4]? arg[4][18] : 0;
  a07=(a02-a07);
  a08=casadi_sq(a07);
  a09=arg[4]? arg[4][19] : 0;
  a09=(a05-a09);
  a10=casadi_sq(a09);
  a08=(a08+a10);
  a08=(a01-a08);
  a08=(a04*a08);
  if (res[0]!=0) res[0][1]=a08;
  a08=arg[4]? arg[4][26] : 0;
  a10=arg[4]? arg[4][20] : 0;
  a10=(a02-a10);
  a11=casadi_sq(a10);
  a12=arg[4]? arg[4][21] : 0;
  a12=(a05-a12);
  a13=casadi_sq(a12);
  a11=(a11+a13);
  a11=(a01-a11);
  a11=(a08*a11);
  if (res[0]!=0) res[0][2]=a11;
  a11=arg[4]? arg[4][27] : 0;
  a13=arg[4]? arg[4][22] : 0;
  a02=(a02-a13);
  a13=casadi_sq(a02);
  a14=arg[4]? arg[4][23] : 0;
  a05=(a05-a14);
  a14=casadi_sq(a05);
  a13=(a13+a14);
  a01=(a01-a13);
  a01=(a11*a01);
  if (res[0]!=0) res[0][3]=a01;
  a03=(2.*a03);
  a03=(a00*a03);
  a03=(-a03);
  if (res[1]!=0) res[1][0]=a03;
  a06=(2.*a06);
  a06=(a00*a06);
  a06=(-a06);
  if (res[1]!=0) res[1][1]=a06;
  a07=(2.*a07);
  a07=(a04*a07);
  a07=(-a07);
  if (res[1]!=0) res[1][2]=a07;
  a09=(2.*a09);
  a09=(a04*a09);
  a09=(-a09);
  if (res[1]!=0) res[1][3]=a09;
  a10=(2.*a10);
  a10=(a08*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][4]=a10;
  a12=(2.*a12);
  a12=(a08*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][5]=a12;
  a02=(2.*a02);
  a02=(a11*a02);
  a02=(-a02);
  if (res[1]!=0) res[1][6]=a02;
  a05=(2.*a05);
  a05=(a11*a05);
  a05=(-a05);
  if (res[1]!=0) res[1][7]=a05;
  a05=arg[2]? arg[2][3] : 0;
  a11=(a11*a05);
  a11=(2.*a11);
  a05=arg[2]? arg[2][2] : 0;
  a08=(a08*a05);
  a08=(2.*a08);
  a11=(a11+a08);
  a08=arg[2]? arg[2][1] : 0;
  a04=(a04*a08);
  a04=(2.*a04);
  a11=(a11+a04);
  a04=arg[2]? arg[2][0] : 0;
  a00=(a00*a04);
  a00=(2.*a00);
  a11=(a11+a00);
  a11=(-a11);
  if (res[2]!=0) res[2][0]=a11;
  if (res[2]!=0) res[2][1]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpc_walk_path_constr_h_e_fun_jac_uxt_zt_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mpc_walk_path_constr_h_e_fun_jac_uxt_zt_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpc_walk_path_constr_h_e_fun_jac_uxt_zt_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mpc_walk_path_constr_h_e_fun_jac_uxt_zt_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void mpc_walk_path_constr_h_e_fun_jac_uxt_zt_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mpc_walk_path_constr_h_e_fun_jac_uxt_zt_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int mpc_walk_path_constr_h_e_fun_jac_uxt_zt_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real mpc_walk_path_constr_h_e_fun_jac_uxt_zt_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpc_walk_path_constr_h_e_fun_jac_uxt_zt_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpc_walk_path_constr_h_e_fun_jac_uxt_zt_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpc_walk_path_constr_h_e_fun_jac_uxt_zt_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s1;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpc_walk_path_constr_h_e_fun_jac_uxt_zt_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    case 4: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mpc_walk_path_constr_h_e_fun_jac_uxt_zt_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpc_walk_path_constr_h_e_fun_jac_uxt_zt_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
