/* This file was automatically generated by CasADi 3.8.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mpc_walk_path_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {28, 1, 1};

/* mpc_walk_path_dyn_disc_phi_fun:(i0[6],i1[3],i2[28])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14;
  a00=arg[0]? arg[0][0] : 0;
  a01=1.6666666666666666e-02;
  a02=arg[0]? arg[0][2] : 0;
  a03=cos(a02);
  a04=arg[0]? arg[0][3] : 0;
  a05=1.0000000000000001e-01;
  a06=arg[1]? arg[1][0] : 0;
  a06=(a05*a06);
  a04=(a04+a06);
  a06=(a03*a04);
  a07=sin(a02);
  a08=arg[0]? arg[0][4] : 0;
  a09=arg[1]? arg[1][1] : 0;
  a09=(a05*a09);
  a08=(a08+a09);
  a09=(a07*a08);
  a06=(a06-a09);
  a09=5.0000000000000003e-02;
  a10=arg[0]? arg[0][5] : 0;
  a11=arg[1]? arg[1][2] : 0;
  a11=(a05*a11);
  a10=(a10+a11);
  a09=(a09*a10);
  a09=(a02+a09);
  a11=cos(a09);
  a12=(a11*a04);
  a09=sin(a09);
  a13=(a09*a08);
  a12=(a12-a13);
  a12=(2.*a12);
  a06=(a06+a12);
  a06=(a06+a12);
  a05=(a05*a10);
  a05=(a02+a05);
  a12=cos(a05);
  a13=(a12*a04);
  a05=sin(a05);
  a14=(a05*a08);
  a13=(a13-a14);
  a06=(a06+a13);
  a06=(a01*a06);
  a00=(a00+a06);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a07=(a07*a04);
  a03=(a03*a08);
  a07=(a07+a03);
  a09=(a09*a04);
  a11=(a11*a08);
  a09=(a09+a11);
  a09=(2.*a09);
  a07=(a07+a09);
  a07=(a07+a09);
  a05=(a05*a04);
  a12=(a12*a08);
  a05=(a05+a12);
  a07=(a07+a05);
  a07=(a01*a07);
  a00=(a00+a07);
  if (res[0]!=0) res[0][1]=a00;
  a00=3.;
  a00=(a00*a10);
  a07=(2.*a10);
  a00=(a00+a07);
  a00=(a00+a10);
  a01=(a01*a00);
  a02=(a02+a01);
  if (res[0]!=0) res[0][2]=a02;
  if (res[0]!=0) res[0][3]=a04;
  if (res[0]!=0) res[0][4]=a08;
  if (res[0]!=0) res[0][5]=a10;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpc_walk_path_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mpc_walk_path_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpc_walk_path_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mpc_walk_path_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void mpc_walk_path_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mpc_walk_path_dyn_disc_phi_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int mpc_walk_path_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mpc_walk_path_dyn_disc_phi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpc_walk_path_dyn_disc_phi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpc_walk_path_dyn_disc_phi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpc_walk_path_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpc_walk_path_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mpc_walk_path_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpc_walk_path_dyn_disc_phi_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
