/* This file was automatically generated by CasADi 3.8.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mpc_walk_path_dyn_disc_phi_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {28, 1, 1};
static const casadi_int casadi_s3[34] = 
  {9, 6, 0, 8, 16, 19, 21, 23,
  25, 0, 1, 2, 3, 5, 6, 7,
  8, 0, 1, 2, 4, 5, 6, 7,
  8, 2, 5, 8, 0, 6, 1, 7,
  2, 8};

/* mpc_walk_path_dyn_disc_phi_fun_jac:(i0[6],i1[3],i2[28])->(o0[6],o1[9x6,25nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26;
  a00=arg[0]? arg[0][0] : 0;
  a01=1.6666666666666666e-02;
  a02=arg[0]? arg[0][2] : 0;
  a03=cos(a02);
  a04=arg[0]? arg[0][3] : 0;
  a05=1.0000000000000001e-01;
  a06=arg[1]? arg[1][0] : 0;
  a06=(a05*a06);
  a04=(a04+a06);
  a06=(a03*a04);
  a07=sin(a02);
  a08=arg[0]? arg[0][4] : 0;
  a09=arg[1]? arg[1][1] : 0;
  a09=(a05*a09);
  a08=(a08+a09);
  a09=(a07*a08);
  a06=(a06-a09);
  a09=5.0000000000000003e-02;
  a10=arg[0]? arg[0][5] : 0;
  a11=arg[1]? arg[1][2] : 0;
  a11=(a05*a11);
  a10=(a10+a11);
  a11=(a09*a10);
  a11=(a02+a11);
  a12=cos(a11);
  a13=(a12*a04);
  a11=sin(a11);
  a14=(a11*a08);
  a13=(a13-a14);
  a13=(2.*a13);
  a06=(a06+a13);
  a06=(a06+a13);
  a13=(a05*a10);
  a13=(a02+a13);
  a14=cos(a13);
  a15=(a14*a04);
  a13=sin(a13);
  a16=(a13*a08);
  a15=(a15-a16);
  a06=(a06+a15);
  a06=(a01*a06);
  a00=(a00+a06);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a06=(a07*a04);
  a15=(a03*a08);
  a06=(a06+a15);
  a15=(a11*a04);
  a16=(a12*a08);
  a15=(a15+a16);
  a15=(2.*a15);
  a06=(a06+a15);
  a06=(a06+a15);
  a15=(a13*a04);
  a16=(a14*a08);
  a15=(a15+a16);
  a06=(a06+a15);
  a06=(a01*a06);
  a00=(a00+a06);
  if (res[0]!=0) res[0][1]=a00;
  a00=3.;
  a00=(a00*a10);
  a06=(2.*a10);
  a00=(a00+a06);
  a00=(a00+a10);
  a00=(a01*a00);
  a02=(a02+a00);
  if (res[0]!=0) res[0][2]=a02;
  if (res[0]!=0) res[0][3]=a04;
  if (res[0]!=0) res[0][4]=a08;
  if (res[0]!=0) res[0][5]=a10;
  a10=(a05*a03);
  a02=2.0000000000000001e-01;
  a00=(a02*a12);
  a10=(a10+a00);
  a10=(a10+a00);
  a00=(a05*a14);
  a10=(a10+a00);
  a10=(a01*a10);
  if (res[1]!=0) res[1][0]=a10;
  a06=(a05*a11);
  a06=(-a06);
  a06=(2.*a06);
  a15=(a05*a07);
  a16=(a06-a15);
  a16=(a16+a06);
  a06=(a05*a13);
  a16=(a16-a06);
  a16=(a01*a16);
  if (res[1]!=0) res[1][1]=a16;
  a16=4.;
  a17=5.0000000000000010e-03;
  a18=(a17*a11);
  a19=(a04*a18);
  a17=(a17*a12);
  a20=(a08*a17);
  a19=(a19+a20);
  a19=(a16*a19);
  a20=1.0000000000000002e-02;
  a21=(a20*a13);
  a22=(a04*a21);
  a20=(a20*a14);
  a23=(a08*a20);
  a22=(a22+a23);
  a19=(a19+a22);
  a19=(a01*a19);
  a19=(-a19);
  if (res[1]!=0) res[1][2]=a19;
  a19=1.;
  if (res[1]!=0) res[1][3]=a19;
  a22=(a04*a11);
  a23=(a08*a12);
  a22=(a22+a23);
  a22=(-a22);
  a22=(2.*a22);
  a23=(a04*a07);
  a24=(a08*a03);
  a23=(a23+a24);
  a23=(a22-a23);
  a23=(a23+a22);
  a22=(a04*a13);
  a24=(a08*a14);
  a22=(a22+a24);
  a23=(a23-a22);
  a23=(a01*a23);
  if (res[1]!=0) res[1][4]=a23;
  a23=(2.*a12);
  a22=(a03+a23);
  a22=(a22+a23);
  a22=(a22+a14);
  a22=(a01*a22);
  if (res[1]!=0) res[1][5]=a22;
  a23=(-a11);
  a23=(2.*a23);
  a24=(a23-a07);
  a24=(a24+a23);
  a24=(a24-a13);
  a24=(a01*a24);
  if (res[1]!=0) res[1][6]=a24;
  a24=(a09*a11);
  a23=(a04*a24);
  a09=(a09*a12);
  a25=(a08*a09);
  a23=(a23+a25);
  a23=(a16*a23);
  a25=(a04*a06);
  a26=(a08*a00);
  a25=(a25+a26);
  a23=(a23+a25);
  a23=(a01*a23);
  a23=(-a23);
  if (res[1]!=0) res[1][7]=a23;
  a02=(a02*a11);
  a15=(a15+a02);
  a15=(a15+a02);
  a15=(a15+a06);
  a15=(a01*a15);
  if (res[1]!=0) res[1][8]=a15;
  if (res[1]!=0) res[1][9]=a10;
  a17=(a04*a17);
  a18=(a08*a18);
  a17=(a17-a18);
  a17=(a16*a17);
  a20=(a04*a20);
  a21=(a08*a21);
  a20=(a20-a21);
  a17=(a17+a20);
  a17=(a01*a17);
  if (res[1]!=0) res[1][10]=a17;
  if (res[1]!=0) res[1][11]=a19;
  a03=(a04*a03);
  a17=(a08*a07);
  a03=(a03-a17);
  a12=(a04*a12);
  a17=(a08*a11);
  a12=(a12-a17);
  a12=(2.*a12);
  a03=(a03+a12);
  a03=(a03+a12);
  a14=(a04*a14);
  a12=(a08*a13);
  a14=(a14-a12);
  a03=(a03+a14);
  a03=(a01*a03);
  if (res[1]!=0) res[1][12]=a03;
  a11=(2.*a11);
  a07=(a07+a11);
  a07=(a07+a11);
  a07=(a07+a13);
  a07=(a01*a07);
  if (res[1]!=0) res[1][13]=a07;
  if (res[1]!=0) res[1][14]=a22;
  a09=(a04*a09);
  a24=(a08*a24);
  a09=(a09-a24);
  a16=(a16*a09);
  a04=(a04*a00);
  a08=(a08*a06);
  a04=(a04-a08);
  a16=(a16+a04);
  a01=(a01*a16);
  if (res[1]!=0) res[1][15]=a01;
  a01=1.0000000000000000e-02;
  if (res[1]!=0) res[1][16]=a01;
  if (res[1]!=0) res[1][17]=a19;
  if (res[1]!=0) res[1][18]=a05;
  if (res[1]!=0) res[1][19]=a05;
  if (res[1]!=0) res[1][20]=a19;
  if (res[1]!=0) res[1][21]=a05;
  if (res[1]!=0) res[1][22]=a19;
  if (res[1]!=0) res[1][23]=a05;
  if (res[1]!=0) res[1][24]=a19;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpc_walk_path_dyn_disc_phi_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mpc_walk_path_dyn_disc_phi_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpc_walk_path_dyn_disc_phi_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mpc_walk_path_dyn_disc_phi_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void mpc_walk_path_dyn_disc_phi_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mpc_walk_path_dyn_disc_phi_fun_jac_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int mpc_walk_path_dyn_disc_phi_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real mpc_walk_path_dyn_disc_phi_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpc_walk_path_dyn_disc_phi_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpc_walk_path_dyn_disc_phi_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpc_walk_path_dyn_disc_phi_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpc_walk_path_dyn_disc_phi_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mpc_walk_path_dyn_disc_phi_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpc_walk_path_dyn_disc_phi_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
