/*
 * MIT License
 *
 * Copyright (c) 2021 NUbots
 *
 * This file is part of the NUbots codebase.
 * See https://github.com/NUbots/NUbots for further info.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef MODULE_EXTENSION_DIRECTOR_HPP
#define MODULE_EXTENSION_DIRECTOR_HPP

#include <memory>
#include <nuclear>
#include <typeindex>
#include <vector>

#include "component/DirectorTask.hpp"
#include "component/ProviderGroup.hpp"

#include "extension/Behaviour.hpp"

#include "message/behaviour/Director.hpp"

namespace module::extension {

    class Director : public NUClear::Reactor {
    public:
        /// A task list holds a list of tasks
        using TaskList = std::vector<std::shared_ptr<component::DirectorTask>>;

        /// A task pack is the result of a set of tasks emitted by a provider that should be run together
        struct TaskPack {
            /// The provider that emitted this task pack
            std::shared_ptr<component::Provider> provider;
            /// The tasks that were emitted by the provider
            TaskList tasks;
        };

        // Only use a single thread at a time for the Director
        static constexpr int concurrency = 1;

    private:
        /// A request to run the specified provider, after a `Wait` task's time has elapsed
        struct WaitFinished {
            /// The provider to run after the `Wait` task's time has elapsed
            std::shared_ptr<component::Provider> provider;
        };

        /**
         * Adds a Provider for a type
         *
         * @param p the ProvideReaction object that was generated by the Behaviour extension
         *
         * @throws std::runtime_error when there is more than one Provide in an on statement
         */
        void add_provider(const ::extension::behaviour::commands::ProvideReaction& provide);

        /**
         * Removes a Provider for a type
         *
         * @param id the id of the reaction we want to remove the Provider for
         *
         * @throws std::runtime_error when the reaction does not provide anything
         */
        void remove_provider(const NUClear::id_t& id);

        /**
         * Finds or creates a root provider for a task and returns it
         *
         * @param root_type the root task type
         *
         * @return the root provider
         */
        std::shared_ptr<component::Provider> get_root_provider(const std::type_index& root_type);

        /**
         * Add a when condition to an existing Provider
         *
         * @param when the description of the When expression from the Behaviour extension
         */
        void add_when(const ::extension::behaviour::commands::WhenExpression& when);

        /**
         * Add a causing condition to an existing Provider
         *
         * @param causing the description of the Causing expression from the behaviour extension
         */
        void add_causing(const ::extension::behaviour::commands::CausingExpression& causing);

        /**
         * Add a needs to an existing Provider
         *
         * @param needs the description of the Needs expression from the behaviour extension
         */
        void add_needs(const ::extension::behaviour::commands::NeedsExpression& needs);

        /**
         * Compares the challenge priorities of two director tasks and returns true if the challenger has priority over
         * the incumbent using challenge priority.
         *
         * i.e. incumbent < challenger
         *
         * The function requires that the challenger's precedence is strictly greater than the incumbent's.
         * This ensures that we don't change tasks unnecessarily when the priority is equal.
         *
         * @param incumbent     the task to compare which is currently the active running task
         * @param challenger    the task to compare which wants to run but is not currently running
         *
         * @return true     if the challenger has strictly higher priority than the incumbent
         * @return false    if the incumbent task has equal or higher priority
         *
         * @throws std::runtime_error if the director's provider ancestry is broken
         */
        [[nodiscard]] bool challenge_priority(const std::shared_ptr<component::DirectorTask>& incumbent,
                                              const std::shared_ptr<component::DirectorTask>& challenger);

        /**
         * Compares the direct priorities of two director tasks and returns true if the challenger has priority over the
         * incumbent.
         *
         * i.e. incumbent < challenger
         *
         * The function requires that the challenger's precedence is strictly greater than the incumbent's.
         * This ensures that we don't change tasks unnecessarily when the priority is equal.
         *
         * @param incumbent     the task to compare which is currently the active running task
         * @param challenger    the task to compare which wants to run but is not currently running
         *
         * @return true     if the challenger has strictly higher priority than the incumbent
         * @return false    if the incumbent task has equal or higher priority
         *
         * @throws std::runtime_error if the director's provider ancestry is broken
         */
        [[nodiscard]] static bool direct_priority(const std::shared_ptr<component::DirectorTask>& incumbent,
                                                  const std::shared_ptr<component::DirectorTask>& challenger);

        /**
         * Remove the provided task from the Director.
         *
         * This function also deals with all the consequences of removing the task including looking to see if a queued
         * task can now be run.
         *
         * @param task the task to remove from the Director
         */
        void remove_task(const std::shared_ptr<component::DirectorTask>& task);

        /**
         * Reevaluates all of the tasks that are queued to execute on a provider group.
         *
         * Each of the tasks in the queue are waiting to use this provider group but cannot for some reason or another.
         * In order to determine if they can now run on the queue we need to look at each queued task and inspect if the
         * provider that created them can now run. We do this by simply trying to run them all again.
         *
         * @param group the group whose queue we want to reevaluate
         *
         * @return true if as a result of reevaluating we changed tasks
         */
        bool reevaluate_group(component::ProviderGroup& group);

        /**
         * Runs a reevaluation on not only the passed group, but any groups that it is using
         *
         * It will run reevaluate_group on the passed group, and then if nothing changes in the group it will look at
         * each of the subtasks. If a subtask is currently the active task in another group it will recursively call on
         * that group. This will terminate once there are no more subtasks that are active in other groups or when
         * calling reevaluate_group results in a change of the currently running task.
         *
         * @param group the group whose queue we want to reevaluate along with all children
         */
        void reevaluate_children(component::ProviderGroup& group);

        /**
         * The result of evaluating how (and if) a task or provider could be executed right now.
         *
         * An evaluation collapses the whole tree of providers, needs, and when/causing relationships below a task
         * into a single answer:
         *  - RUNNABLE: everything below is available, `provider` (plus `providers`) can be executed immediately
         *  - PUSHABLE: it can't run yet, but running the providers in `pushes` would cause the when conditions it
         *              is missing to be met (see Causing), after which it could run
         *  - BLOCKED:  it can't run and there is nothing we can push to change that, all we can do is watch the
         *              groups in `watching` and try again when one of them changes
         */
        struct Evaluation {
            /// How far this evaluation got towards being executable
            enum State {
                /// Everything needed is available, this can be executed now
                RUNNABLE,
                /// Blocked on when conditions, but pushing the providers in `pushes` would unblock it
                PUSHABLE,
                /// Cannot run and cannot push, wait for one of `watching` to change
                BLOCKED,
            };

            /// How far this evaluation got towards being executable
            State state = BLOCKED;
            /// The provider that this evaluation would execute
            std::shared_ptr<component::Provider> provider;
            /// The providers needed by the requirements below `provider`, flattened
            std::vector<std::shared_ptr<component::Provider>> providers;
            /// The provider groups this evaluation would occupy if executed
            std::set<std::type_index> used;
            /// The provider groups that stopped us from running, to watch for changes
            std::set<std::type_index> watching;
            /// How many pushes removed from being runnable the providers in `pushes` are.
            /// When multiple when conditions chain through Causing providers (a ladder), only the deepest level can
            /// be pushed first, then once its state change propagates the next level becomes pushable.
            int push_depth = 0;
            /// The providers that need to be pushed before this evaluation can run
            std::set<std::shared_ptr<component::Provider>> pushes;
        };

        /**
         * Merges the pushes of a child evaluation into its parent.
         *
         * All of a provider's requirements must be met for it to run, so when several of them need pushes only the
         * deepest ones can be pushed first (the shallower ones can't act until the deeper state changes propagate).
         * Within a single provider group the pushes are intersected, as only a provider that satisfies every
         * requirement that wants to push that group will work for all of them.
         *
         * @param parent the evaluation accumulating the pushes
         * @param child  the child evaluation whose pushes are being merged in
         *
         * @return false if an intersection came up empty meaning the requirements need conflicting pushes
         */
        static bool merge_pushes(Evaluation& parent, const Evaluation& child);

        /**
         * Evaluates how a task could be executed by evaluating the provider group it targets.
         *
         * @param task the task to evaluate, also used as the authority token for permission checks
         * @param used the provider groups already used by earlier tasks in the pack which we cannot reuse
         *
         * @return the evaluation for the best way to run this task
         */
        Evaluation evaluate_task(const std::shared_ptr<component::DirectorTask>& task,
                                 const std::set<std::type_index>& used);

        /**
         * Evaluates the providers of a group in declaration order and selects the first that can run.
         *
         * If no provider is runnable but one is pushable the first pushable one is selected instead. The groups that
         * blocked every rejected provider are accumulated into `watching` so the caller can watch all of them, not
         * just the ones from the selected provider.
         *
         * If the group is currently being pushed and the authority cannot outrank the pushing task, only the pushed
         * provider is considered.
         *
         * @param type      the provider group to evaluate
         * @param authority the task used as the authority token for permission checks
         * @param visited   the provider groups already visited on this path, to prevent loops
         * @param used      the provider groups already used elsewhere in the solution which we cannot reuse
         *
         * @return the evaluation for the best provider in this group
         */
        Evaluation evaluate_group(const std::type_index& type,
                                  const std::shared_ptr<component::DirectorTask>& authority,
                                  const std::set<std::type_index>& visited,
                                  const std::set<std::type_index>& used);

        /**
         * Evaluates a single provider by recursively evaluating its unmet when conditions and its needs.
         *
         * The provider is BLOCKED if it would form a loop, if the authority cannot outrank the group's active task,
         * if its group was already used elsewhere in the solution, or if any of its requirements are BLOCKED.
         * It is PUSHABLE if all requirements are met except when conditions that could be pushed via Causing
         * providers. Otherwise it is RUNNABLE.
         *
         * @param provider  the provider to evaluate
         * @param authority the task used as the authority token for permission checks
         * @param visited   the provider groups already visited on this path, to prevent loops
         * @param used      the provider groups already used elsewhere in the solution which we cannot reuse
         *
         * @return the evaluation for this provider
         */
        Evaluation evaluate_provider(const std::shared_ptr<component::Provider>& provider,
                                     const std::shared_ptr<component::DirectorTask>& authority,
                                     std::set<std::type_index> visited,
                                     std::set<std::type_index> used);

        /**
         * Evaluates which providers could be pushed to make an unmet when condition become true.
         *
         * Candidates are Provide providers in currently running groups whose Causing statement satisfies the when
         * condition. A candidate that is itself pushable (its own when conditions unmet but pushable) contributes
         * its deeper pushes instead of itself; pushing those first starts the chain. Among viable candidates the
         * ones fewest pushes away from running are chosen.
         *
         * @param when      the unmet when condition to satisfy
         * @param authority the task used as the authority token for permission checks
         * @param visited   the provider groups already visited on this path, to prevent loops
         *
         * @return a PUSHABLE evaluation holding the providers to push, or BLOCKED if there are no viable candidates
         */
        Evaluation evaluate_causing(const component::Provider::WhenCondition& when,
                                    const std::shared_ptr<component::DirectorTask>& authority,
                                    const std::set<std::type_index>& visited);

        /**
         * Runs the passed task on the passed provider.
         *
         * @param task          the task we are running
         * @param provider      the provider that we are running the task on
         * @param run_reason    the reason that we are running this task
         */
        void run_task_on_provider(const std::shared_ptr<component::DirectorTask>& task,
                                  const std::shared_ptr<component::Provider>& provider,
                                  const ::extension::behaviour::RunReason& run_reason);

        /**
         * The level of execution that a set of tasks was able to achieve, lower levels are better.
         *
         * When passed as an argument to run_tasks it is the worst level that the tasks are allowed to operate at.
         * For example, if a non optional pack could only achieve PUSH, the optional tasks that follow it are limited
         * to PUSH as well so they cannot execute for real while their non optional siblings are still queued.
         */
        enum RunLevel {
            /// We can run all our tasks on providers now
            OK,
            /// We can't run all our tasks on providers now, but we can push to fix our requirements
            PUSH,
            /// We can't run all our tasks on providers now, and we can't push to fix our requirements
            BLOCKED
        };

        /**
         * The result of running a set of tasks
         */
        struct RunResult {
            /// The level of execution that we were able to do
            RunLevel run_level;
            /// The set of provider groups that we used
            std::set<std::type_index> used;
        };

        /**
         * Tries to execute tasks in the pack, but only up to the passed run level.
         *
         * The passed run level will limit what types of execution are open to us. For example, if the required pack was
         * only able to execute up to the PUSH level, then we will only execute up to the PUSH level for the optional
         * packs that come afterward.
         *
         * @param group     the provider group that created this pack
         * @param pack      the pack of tasks that we are trying to execute
         * @param run_level the level of execution that we are allowed to do
         * @param used      the set of provider groups that are already used that we can't use again
         *
         * @return the run level that we were able to execute up to and the set of provider groups that we used
         */
        RunResult run_tasks(component::ProviderGroup& group,
                            const TaskList& pack,
                            const RunLevel& run_level,
                            const std::set<std::type_index>& used);

        /**
         * Looks at all the tasks that are in the pack and determines if they should run, and if so runs them.
         *
         * This function will ensure that if this pack is to be executed it can be executed as a whole. That means that
         * all of the non optional tasks in it are able to run now given the state of the system. If the system is
         * unable to run due to priority or due to a when condition not met it will not run any of the tasks in this
         * pack, but enqueue them on the relevant providers.
         *
         * In the event that `When` conditions needs to be met by this pack and it has sufficient priority, it may also
         * place this provider group into a "Pushing" state whereby it forces another provider group into a state where
         * it will make the system reach the causing it requires.
         *
         * @param pack the task pack that represents the queued tasks
         */
        void run_task_pack(const TaskPack& pack);

    public:
        /// Called by the powerplant to build and setup the Director reactor.
        explicit Director(std::unique_ptr<NUClear::Environment> environment);

    private:
        /**
         * Emits the director state if it has changed.
         */
        void emit_state();

        /// A list of Provider groups
        std::map<std::type_index, component::ProviderGroup> groups;
        /// Maps reaction_id to the Provider which implements it
        std::map<NUClear::id_t, std::shared_ptr<component::Provider>> providers;

        /// A source for unique reaction ids when making root task providers. Starts at 0 and wraps around to maxvalue.
        NUClear::id_t unique_id_source = 0;

        /// The protobuf message that holds the current state of the director
        message::behaviour::DirectorState director_state;
        /// The last emitted state, used to check for changes
        bool state_changed = false;
    };

}  // namespace module::extension

// Director stats (eg trace) are turned off on normal BehaviourTasks, we do this to WaitFinished as well
// This is due to computational issues when stats are on in the Director
namespace NUClear::dsl::operation {
    template <>
    struct EmitStats<module::extension::Director::WaitFinished> : std::false_type {};
}  // namespace NUClear::dsl::operation

#endif  // MODULE_EXTENSION_DIRECTOR_HPP
