#ifndef MODULE_NETWORK_MCPSERVER_HPP
#define MODULE_NETWORK_MCPSERVER_HPP

#include <deque>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/dynamic_message.h>
#include <map>
#include <memory>
#include <mcp/http_server_host.hpp>
#include <mutex>
#include <nuclear>
#include <string>
#include <vector>

namespace module::network {

class MCPServer : public NUClear::Reactor {
private:
    /// @brief Stores configuration values
    struct Config {
        /// @brief Address the MCP endpoint binds to
        std::string host = "127.0.0.1";
        /// @brief Port the MCP endpoint listens on
        int port = 8080;
        /// @brief URL path of the Streamable HTTP endpoint
        std::string path = "/mcp";
        /// @brief Origin allowlist for DNS-rebinding protection
        std::vector<std::string> allowed_origins{};
        /// @brief Message types buffered for the model, keyed by message name
        std::map<std::string, bool> messages{};
        /// @brief Maximum number of messages held in the buffer before the oldest are dropped
        size_t max_buffered_messages = 100;
    } cfg;

    /// @brief A single message captured for the model to read later
    struct BufferedMessage {
        /// @brief When the message was captured
        NUClear::clock::time_point timestamp;
        /// @brief Fully qualified message name, e.g. message.input.Sensors
        std::string type;
        /// @brief Protobuf type name used to look up the descriptor, e.g. protobuf.message.input.Sensors
        std::string pb_name;
        /// @brief The message serialised as protobuf wire format
        std::vector<uint8_t> payload;
    };

    /// @brief The MCP Streamable HTTP host, created on Startup and stopped on Shutdown
    std::unique_ptr<mcp::HttpServerHost> host{};

    /// @brief Buffered messages waiting to be dumped to the model, oldest first
    std::deque<BufferedMessage> buffer{};
    /// @brief Guards buffer, written by reactions and read by MCP server threads
    std::mutex buffer_mutex{};

    /// @brief Descriptors for every message type, so payloads can be decoded to JSON at runtime.
    /// The generated C++ protobuf classes are lite and have no reflection, so the descriptors are embedded
    /// by generate_handles.py and used to build full dynamic messages when dumping the buffer.
    google::protobuf::DescriptorPool descriptor_pool{};
    /// @brief Builds dynamic protobuf messages from the descriptors in descriptor_pool
    google::protobuf::DynamicMessageFactory message_factory{};

    /// @brief Reactions that capture each message type, disabled until enabled by configuration
    std::map<std::string, ReactionHandle> handles{};

    /// @brief Create the (initially disabled) reaction that buffers messages of type T
    template <typename T>
    void add_handle(const std::string& type, const std::string& pb_name) {
        handles[type] =
            on<Trigger<T>, Single, Priority::LOW>()
                .then(type,
                      [this, type, pb_name](const T& msg) {
                          // Serialise to protobuf wire format, decoded to JSON when the buffer is dumped
                          auto payload = NUClear::util::serialise::Serialise<T>::serialise(msg);

                          std::lock_guard<std::mutex> lock(buffer_mutex);
                          buffer.push_back(
                              BufferedMessage{NUClear::clock::now(), type, pb_name, std::move(payload)});
                          while (buffer.size() > cfg.max_buffered_messages) {
                              buffer.pop_front();
                          }
                      })
                .disable();
    }

    /// @brief Register a buffering handle for every message type (generated by generate_handles.py)
    void register_handles();

    /// @brief Fill descriptor_pool with the descriptors of every message type (generated by generate_handles.py)
    void register_descriptors();

    /// @brief Register the tools exposed to each MCP session
    void register_tools(mcp::Server& server);

public:
    /// @brief Called by the powerplant to build and setup the MCPServer reactor.
    explicit MCPServer(std::unique_ptr<NUClear::Environment> environment);
};

}  // namespace module::network

#endif  // MODULE_NETWORK_MCPSERVER_HPP
