/* Generated by codegen/generate_solver.py (acados v0.6.0); do not edit. */
#ifndef MPC_WALK_PATH_LAYOUT_H
#define MPC_WALK_PATH_LAYOUT_H

#define MPC_WALK_PATH_DT 0.1
#define MPC_WALK_PATH_MAX_OBSTACLES 4

/* Per-stage parameter vector layout */
#define MPC_WALK_PATH_P_TARGET 0
#define MPC_WALK_PATH_P_GATE 3
#define MPC_WALK_PATH_P_BEARING 4
#define MPC_WALK_PATH_P_W_POSITION 5
#define MPC_WALK_PATH_P_W_HEADING 6
#define MPC_WALK_PATH_P_W_FACE 7
#define MPC_WALK_PATH_P_HUBER_DELTA 8
#define MPC_WALK_PATH_P_W_EFFORT 9
#define MPC_WALK_PATH_P_W_RATE 12
#define MPC_WALK_PATH_P_OBSTACLE_RADIUS 15
#define MPC_WALK_PATH_P_OBSTACLES 16
#define MPC_WALK_PATH_P_ACTIVE 24
#define MPC_WALK_PATH_NP 28

#endif /* MPC_WALK_PATH_LAYOUT_H */
