# Find our globally shared libraries:
FIND_PACKAGE(LibGFortran REQUIRED)
FIND_PACKAGE(Protobuf REQUIRED)
FIND_PACKAGE(CATCH REQUIRED)
FIND_PACKAGE(YAML-CPP REQUIRED)
FIND_PACKAGE(muParserX REQUIRED)
FIND_PACKAGE(fmt REQUIRED)

# Set include directories and libraries:
INCLUDE_DIRECTORIES(SYSTEM ${BLAS_INCLUDE_DIRS})
INCLUDE_DIRECTORIES(SYSTEM ${PROTOBUF_INCLUDE_DIRS})
INCLUDE_DIRECTORIES(SYSTEM ${CATCH_INCLUDE_DIRS})
INCLUDE_DIRECTORIES(SYSTEM ${YAML-CPP_INCLUDE_DIRS})
INCLUDE_DIRECTORIES(SYSTEM ${muParserX_INCLUDE_DIRS})
INCLUDE_DIRECTORIES(SYSTEM ${fmt_INCLUDE_DIRS})

SET(NUCLEAR_ADDITIONAL_SHARED_LIBRARIES
    ${BLAS_LIBRARIES}
    ${LIBGFORTRAN_LIBRARIES}
    ${PROTOBUF_LIBRARIES}
    ${YAML-CPP_LIBRARIES}
    ${muParserX_LIBRARIES}
    ${fmt_LIBRARIES}
    -ldl
    -lbacktrace
)
